### PR TITLE
Add missing textdomains to newly created strings.

### PR DESCRIPTION
**Pull request by pedro-mendonca**
Maybe it could be better without the `<strong>` html tags?

### CODE REVIEW

**Comment by sybrew** [comment]
Hi Pedro,

Thanks again for your keen eye! 

I think removing the "strong" tags would be best. Although I still want to highlight it.
I wish to escape all input from the translators. Because sometimes, although unlikely, nasty things can slip through.

I'll see if I can make something nice from this.

Cheers!

**Comment by pedro-mendonca** [comment]
So, striping out the <strong> tags can work, putting outside the gettext funcion.

**Comment by pedro-mendonca** [comment]
Instead `__( '<strong>incorrectly</strong>'`, it could be something like `'<strong>' . __( 'incorrectly', 'autodescription' ) . '</strong>'`.

Still, let me suggest that it's a way better practice to have the whole sentence as a complete string, keeping the words "incorrectly" and "deprecated" included, as it was in the beggining. You might want to keep the <strong> tags out of it, as variables, but the string is getting too many strings already. Might need some comments to help translators.

**Comment by pedro-mendonca** [comment]
As a complete sentence, it would be like this:
`sprintf( esc_html__( '%1$s was called %2$sincorrectly%3$s. %4$s', 'autodescription' ), esc_html( $function ), '<strong>', '</strong>', 'autodescription' ), esc_html( $version ) )`

I think it's ok, and better for translators to understand the context. Having just "deprecated" or "incorrectly" can lead to several translation errors, like gender or number issues.

**Comment by pedro-mendonca** [comment]
I've submitted this new https://github.com/sybrew/the-seo-framework/pull/30/commits/9a0d9f4735aaa8decfb9646ea6922a30e249a96c to show you what I meant.

**Comment by sybrew** [comment]
I liked the suggestion of https://github.com/sybrew/the-seo-framework/pull/30#issuecomment-247928484 best :).

It gives less for the translators to think about, it looks a lot like the default WordPress deprecation handler notification and the code is more readable.

**Comment by pedro-mendonca** [comment]
Do you mean the suggestion I've made in the second paragraph? The PR is updated according to that.

**Comment by sybrew** [comment]
I mean this:

> Instead `__( '<strong>incorrectly</strong>', 'autodescription' )`, it could be something like `'<strong>' . esc_html__( 'incorrectly', 'autodescription' ) . '</strong>'`.

**Comment by pedro-mendonca** [comment]
The problem with that solution is that translators will need to check out code to understand it's context. It's always a better practice to have complete sentences.
Example: "deprecated" can be singular or plural, and in latin languages can also have a gender -> "obsoleto", "obsoletos", "obsoleta", "obsoletas", depending on the sentence subject.

**Comment by sybrew** [comment]
That's where translation comments come in. Which are either achieved by `_x()` or a PHP comment.
WordPress' translation services look at these comments.

Example: https://github.com/sybrew/the-seo-framework/blob/ff022afb27252319f691cf2d9eaed7a6a1d9cb25/inc/classes/debug.class.php#L119

**Comment by pedro-mendonca** [comment]
Yes, I know that.
I'll update the PR in a minute.

**Pull request merged**
