### PR TITLE
WPML compatibility

### PR DESCRIPTION
**Pull request by vukvukovich**
We could also filter query arguments so we can separate WPML compatibility into separate file.

Separate file might come handy since we need to disable WPML "All languages" option for your plugin.
If not, please tell me where to put code to disable this option.

Cheers!

### CODE REVIEW

**Comment by sybrew** [comment]
Hi @vukvukovich, 

I've suppressed filters at that stage because enabling those filters use lots of resources and to prevent any plausible bugs.
Also, a lot of compatibility has been considered throughout the URL generation.

I'll definitely will look into the cause and effect of your commit with various plugins. In the meantime, I'm afraid there's no way around this other than using your adjusted branch.

But filtering those arguments does sound like a great alternative to me (it saves me loads of time testing).
Don't forget: `wp_parse_args( $args, $defaults );`

Cheers!

**Comment by sybrew** [comment]
Related: #36

**Comment by vukvukovich** [comment]
Hi @sybrew 

I've updated MR. 

Tested and everything now works properly.
You'll notice I've separated WPML functions into separate file.
I have also saw that there are few other old WPML related functions that you can move too.

Best regards!

**Comment by sybrew** [comment]
Hi @vukvukovich,

Thanks for this! I'll test it next year 😉.
It's not 100% according to the coding style of The SEO Framework, so I'll clean it up a bit before I merge it. If there are any issues found I'll let you know.

Happy New Year!

**Comment by vukvukovich** [comment]
Hey,

Sure, no problem, just tell me what to correct and I'll make changes.

All the best in 2017!  🎉 😄

**Comment by sybrew** [comment]
Hi @vukvukovich,

## Brainstorm
I like the idea of having WPML compatibility listed in an external file. So we exactly know what's happening and can keep up with the changes, if any.
 
Nevertheless, it's not per standard for The SEO Framework to have its compatibility functions in external vendor files &mdash; as we then lose overhead of what's happening. Then again, as a counter argument, that file could be included in a `inc/vendor/wpml.php` file - and be loaded whenever WPML is detected.

This would lead into implementing more filters, which is very beneficial for other plugins as well. At the same time, it will speed up the plugin when that functionality is required &mdash; now it will always check for WPML implementation.

What do you think?

## Prevent mistakes with filter implementation
The additional filters for the sitemap, should be as such:
```
$defaults = array(
	'posts_per_page'   => $totalpages,
	'post_type'        => 'page',
	'orderby'          => 'date',
	'order'            => 'ASC',
	'post_status'      => 'publish',
	'fields'           => 'ids',
	'cache_results'    => false,
	'suppress_filters' => true,
	'no_found_rows'    => true,
);

/**
 * Applies filters the_seo_framework_sitemap_pages_query_args : array
 * @since 2.8.0
 *
 * @param array $args The query arguments.
 */
$args = (array) apply_filters( 'the_seo_framework_sitemap_pages_query_args', array() );
$wp_query->query = $wp_query->query_vars = wp_parse_args( $args, $defaults );
```

I see that the previously implemented `wp_parse_args()` usage was a mistake from my side, it probably got merged or moved around incorrectly in the past.

I'll definitely move in the filters for 2.8.0; additional improvements unfortunately will be moved to 2.9.0 or 2.8.x. So I believe they can be removed from the pull request.

I noticed you're part of the compatibility team for WPML - so I trust your changes to be effective and in working order 😄. I picked up on [this discussion](https://wpml.org/forums/topic/when-change-the-admin-language-sitemap-links-changes/) regarding this pull request, so I'll keep my eyes on that too for any conflicts.

I await your reply. Thanks!

**Comment by vukvukovich** [comment]
Hello,

I totally agree that compatibility files should be separated, since it is much easier to maintain compatibility with other plugins.

Ok, you are saying the file `functions/wpml.php` needs to be moved to`inc/vendor/wpml.php`, right?
Is it ok to load it in `load.php`?

Also about filtering the arguments, imho we could leave out `wp_parse_args()` and leave it for the developer who is filtering the arguments to use it. Because we are doubling the work there than.

Tell me what you think, so I can make necessary changes to MR.

Cheers!

**Comment by sybrew** [comment]
Hi @vukvukovich,

**Vendor files**
Then it shall be done 👍. See next paragraph.

**Scheduled for 2.9.0**
With TSF 2.8.0 being in development far too long already: I'll make a template and its auto-loader for all this in at 2.9.0 development kickoff; so you don't have to worry about it for now. I'll also shift those filter implementations for 2.9.0 release, and I hope to have 2.9.0 done within a month (at most 2) after 2.8.0. It will be the "compatibility" version 😄. 

**wp_parse_args**
About `wp_parse_args()`, it's very fast &mdash; especially in PHP 7+. And if I ever were to require new arguments (say, WordPress changes the lot), then no additional changes need to be made within the filter files.
Unless if all filters correctly "add onto" the input parameter; which I can't expect (so I need to use isset/empty at all times). 
Thus it also prevents loss of array indexes, and that will prevent errors and additional checks, which in turn improves performance. It also improves code readability.

With all that, I believe it's better to use `wp_parse_args`: Cleaner code, less overhead.

**Comment by vukvukovich** [comment]
Hi, 

We should wait with this implementation, since I've just spotted something not properly handled. 
Give me few moments to test it and I'll get back to you.

Cheers!

**Comment by vukvukovich** [comment]
Hello,

Can you please tell me where would you like for wpml.php file to be placed and loaded? 
I would like to update pull request.

Cheers!

**Comment by sybrew** [comment]
Hi @vukvukovich,

The planned loader would load this file for WPML:
`/inc/compat/plugin-wpml.php`

**Comment by vukvukovich** [comment]
Ok, and to load it as it is already in the `load.php`?

**Comment by sybrew** [comment]
That's to be determined, the loader would cache the instance and can be injected on-the-fly to save resources. It also depends on how the contents of the file are set up 😄 

i.e. some plugins, like WooCommerce, only require compatibility on specific pages. So the compatibility file doesn't need to be loaded on "https://example.com/sitemap.xml".

**Comment by sybrew** [comment]
Hi @vukvukovich,

I've laid out a template. It's loaded on [`plugins_loaded` priority 5](https://github.com/sybrew/the-seo-framework/blob/1de2acadde82a629d58bb8f7dd0a522f885ef9a4/inc/classes/init.class.php#L68):
https://github.com/sybrew/the-seo-framework/blob/master/inc/compat/plugin-wpml.php

Cheers 😄

**Comment by vukvukovich** [comment]
Hi @sybrew,

I've checked and that fix was not proper one. This is where we are now:

**1.** We do not need to filter args since [Google standards](https://support.google.com/webmasters/answer/2620865?hl=en) are dictating that for every post all language URLs need to be generated. 

So it is ok how posts are queried but we have problem with how URLs for posts are generated.
It is most probably issue here `\The_SEO_Framework\Generate_Url::the_url` and `\The_SEO_Framework\_get_relative_wmpl_url`.

Lets see if you have a clue where problem may be out of the box, or we need to debug it deeply and find it out.

**2.** We have issue when "All Languages" are selected, since it appends "all" to the URL structure. For now I had solution for this by removing it from the admin switcher, but I am sure this problem will disappear too when issue NO. 1 is resolved.

Cheers

**Comment by sybrew** [comment]
Hi @vukvukovich,

**About 1:**
Regarding the linked to Google document, this would mean that we will need to query each language in the sitemap. This would directly mean that the sitemap needs to be reworked - or a separated module for WPML needs to be created.

**About 2:**
That's not good! I believe we can filter the `all` part within these lines:
https://github.com/sybrew/the-seo-framework/blob/6c1dcc8ca81109e502e709fcc95231fd5626651c/inc/compat/plugin-wpml.php#L114-L129 where `$current_lang` would be `all`.

I'm not sure how this actually reflects back to 1.

**Comment by vukvukovich** [comment]
1. As far as I know, by querying with `suppress_filters => true` we are getting all posts. Only URL generated are problems, at least I think so.
2. Whatever suits you better. This reflects by giving bad permalinks in general sitemap if generated from "All languages"

**Comment by sybrew** [comment]
Hi @vukvukovich,

1. For this to work properly, it also requires `hreflang` links, in a `xhtml:link` wrapper. This is a module we currently don't support.
For subdomain-enabled languages, it would even be best for each to have their own sitemap.

All of this requires a tailored solution, as per example below:

```
<!-- What WPML requires: -->
<url>
	<loc>http://www.example.com/english/</loc>
	<xhtml:link rel="alternate" hreflang="de" href="http://www.example.com/deutsch/" />
	<xhtml:link rel="alternate" hreflang="de-ch" href="http://www.example.com/schweiz-deutsch/" />
	<xhtml:link rel="alternate" hreflang="en" href="http://www.example.com/english/" />
</url>

<!-- What TSF gives: -->
<url>
	<loc>http://www.example.com/english/</loc>
</url>
<url>
	<loc>http://www.example.com/deutsch/</loc>
</url>
<url>
	<loc>http://www.example.com/schweiz-deutsch/</loc>
</url>
```

2. Is "all languages" visible by visitors, or only the admins? If it's the former, then this is a bug that should be solved ASAP; so far I haven't been able to detect this.

**Comment by vukvukovich** [comment]
1. Exactly, so we can only say that at the moment SEO Framework is not compatible with WPML plugin.
2. All languages is available to all users in the backend. I can update pull request with code which is removing it from the switcher.

**Comment by sybrew** [comment]
1. Untrue, with this reasoning it essentially means that WPML is incompatible with all sitemap and SEO plugins. But that's a discussion for another topic.
The sitemap is merely a tool for Search Engines, which is this case doesn't help Google understand the language structure - which is fine... if:
What essentially needs to be done is that WPML should output a header tag stating its language, if I'm not mistaken, this is already done, correct?

2. Then this is no bug 😄, but merely an inconvenience that could be "improved".

**Comment by vukvukovich** [comment]
1. You mean adding `hreflang`? If that so, yes. But users need to be aware that sitemap creation is not compatible.

2. I already have solution, do you want me to update PR?

**Comment by sybrew** [comment]
1. If that's the case, then the sitemap is compatible 😄, it just isn't _complete_. Google listens to more than one signal. See https://support.google.com/webmasters/answer/189077?hl=en where they imply the sitemap is optional: "instead ... you can".
2.  Sure thing! Brilliant, thanks! 😄

**Comment by sybrew** [comment]
1) If this is mainly about annoying/flooding issue reports, I think we could write a "go here for more info" or "please read this guide" page. I do not want to disable this functionality without a notification (which could lead to more reports).

We could write something that will add hreflangs, ETA 1 day's work.

Mainly:
1. Add a filter that will capture additional sitemap entries (which is OK).
2. Fill in those entries with hreflang urls (we **must capture the related post IDs**).
3. Disable other languages in the sitemap: **filter the query**. To each language their own sitemap.

2) Please note: All options are global, the language switcher doesn't affect these options. 
However, your pull request does fix all internal links, thanks! I'm going to clean it up and merge it.

**Comment by vukvukovich** [comment]
1. I am not sure I understand why you would have separate sitemaps per language when Google standard are stating one all together sitemap?

2. If you want me to clean it up, just tell me what :)

**Comment by sybrew** [comment]
1. You're absolutely right! :) I see that Google's example also lists related URLs [back and forth](https://support.google.com/webmasters/answer/2620865?hl=en).
2. I already cleaned it up 😄. Thanks!

**Comment by sybrew** [comment]
Because the sitemap's so extremely server taxing, I'm going to have to loop the filter to prevent additional memory heap. I'll take on this job 😄 .

Is there a go-to function in WPML to find alternative language links, including their locations and hreflang?
Maybe this info can even be caught in the WP_Query call to reduce database calls?

**Comment by vukvukovich** [comment]
Sure, great.

You could use `wpml_element_trid` filter to get trid then `wpml_get_element_translations` filter to get translated posts

**Pull request merged**
