### PR TITLE
Robots txt bug fixes

### PR DESCRIPTION
**Pull request by asgeo1**
This PR fixes a few issues I found with the plugin with regards to how robots.txt is being generated.

### CODE REVIEW

**Comment by sybrew** [comment]
Thank you so much, Adam!

The `can_do_sitemap_robots()` method was used to determine if it's at all feasible. That's why the second option check wasn't installed. Things have changed, so I'll check the dependencies before implementation.

I don't like non-strict checks, so I made it strict again with a typesetter.

I dislike composer (because of its library altering properties), but I would love to support it. I'll see how it works out before committing.

Will look at merging this PR a bit later. I have a lot of non-committed changes locally that might break the PR or vice-versa; thus will cause me to flatten or otherwise fix my branch.

**Comment by sybrew** [comment]
P.S. How did you come to the conclusion it required PHP 5.3.2 rather than [5.3.0](https://github.com/sybrew/the-seo-framework/blob/master/inc/functions/plugin-test-server.php#L42)?

**Comment by sybrew** [comment]
Related: https://github.com/sybrew/the-seo-framework/issues/130

**Comment by asgeo1** [comment]
Oh, I copied a composer.json from another Wordpress plugin that I use, then updated all the values.  I left the version of PHP as is, as I didn't know what would be a better minimum version. Feel free to change it.

I think adding composer support is a good idea, it seems to be the best package manager for PHP. 

Myself and quite a few other Wordpress developers, are using https://roots.io now for Wordpress now. It's Wordpress, but they've added Composer support for dependencies, Vagrant for development, and a deployment process, and a bunch of other development "best practices".

Once you get used to pulling in your Wordpress plugins via composer, you'll love it. Now I can keep plugins for all my Wordpress sites (including staging, production, development) easily in sync.

Just adding that composer.json is enough to support Composer, you don't need to do anything else. I don't think it will alter your library in any other way.  I'm pulling in your plugin via Composer now, and it works great.

**Pull request merged**
