### PR TITLE
Delete composer.json

### PR DESCRIPTION
**Pull request by vinkla**
Since we don't provide versions through GitHub we can download this package with WordPress Packagist instead.

### CODE REVIEW

**Comment by sybrew** [comment]
Or.... I could start tagging 😄 What do you think?

**Comment by vinkla** [comment]
> Or.... I could start tagging 😄 What do you think?

Maybe, it depends on the purpose. If anyone wants to extend this plugin then I would sa y go for it. Though, if this is just to submit it to Packagist then there is no real need to release multiple versions. It would just mean more work for you.

**Comment by sybrew** [comment]
It's just a couple of clicks, I push simultaneously anyway...

When done, everything's more maintainable, and referred to more easily. In the end we'd have a better hierarchy overall. 
I believe this goal should be achieved, regardless; so, to have Composer work with it is a nice side-effect.

In any case, the current state of the master branch is stable, so there's no rush.

**Comment by vinkla** [comment]
Okay, sounds good. We don't want other developers to use the master branch.

**Comment by sybrew** [comment]
Great 😄 I'll set up a new tag for 2.9.3 at the end of this week, and will adjust composer.json accordingly shortly after.

**Pull request closed without merging**
